CREATE TABLE tb_user (
                         id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         userid VARCHAR2(255) NOT NULL UNIQUE,
                         password VARCHAR2(255) NOT NULL,
                         testtext VARCHAR2(255) NOT NULL
)