CREATE TABLE IF NOT EXISTS tb_user (
       id BIGINT AUTO_INCREMENT PRIMARY KEY,
       userid VARCHAR(255) NOT NULL UNIQUE,
       password VARCHAR(255) NOT NULL,
       testtext VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;