CREATE TABLE IF NOT EXISTS tb_user (
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid      VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    encode   BOOLEAN DEFAULT FALSE,
    CONSTRAINT pk_tb_user PRIMARY KEY (id)
);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_uid UNIQUE (uid);